README.md
This changelist fixes the front-page link to the LICENSE file for the OpenPBR project.
=> Fix front-page link to license file

reference/open_pbr_surface.mtlx
This changelist removes the legacy Standard Surface approximation of the darkening and saturation of base colors under coatings.
In a future version of OpenPBR, our plan is to implement this coat darkening in a more subtle, physically based fashion, but the current approximation is too far from this ground truth to be useful.
=> Remove Standard Surface approximation of coat darkening

examples/open_pbr_aluminum_brushed.mtlx, examples/open_pbr_carpaint.mtlx, examples/open_pbr_glass.mtlx, examples/open_pbr_honey.mtlx, examples/open_pbr_ketchup.mtlx, examples/open_pbr_lightbulb.mtlx, examples/open_pbr_pearl.mtlx, examples/open_pbr_soapbubble.mtlx, examples/open_pbr_surface_default.mtlx, examples/open_pbr_velvet.mtlx
Here's a collection of example materials, in .mtlx format, that cover most of the parameters found in the OpenPBR specification, as suggested in this Slack thread: https://academysoftwarefdn.slack.com/archives/C06365EAQMP/p1698709666974279
- Any parameters that would’ve been the same as the default have been omitted, to keep the files as minimal as possible, with potential loss of clarity in some cases. Let me know if there are any concerns with this.
- Scene unit for the test renders was set to centimeters. This brings up something I find a bit confusing, why the Subsurface Radius unit isn’t specified in the mtlx file, when the goal is to unify material parameters across applications? Subsurface materials will look different depending on the users scene units. Why is the unit not …
=> Adding example materials

reference/open_pbr_surface.mtlx
This changelist updates the anisotropy logic in the OpenPBR reference graph to match the specification.
To improve clarity and encapsulation, the new logic has been added as an 'open_pbr_anisotropy' node, which is then leveraged in the shading model graph as needed.
=> Update anisotropy in reference graph

index.html, parametrization.md.html, reference/open_pbr_surface.mtlx
Also improve wording/formatting in the spec Translucent base section.
This addresses the points raised in https://github.com/AcademySoftwareFoundation/OpenPBR/issues/148.
=> Fix transmission implementation and improve specification

index.html, parametrization.md.html, reference/open_pbr_surface.mtlx
As discussed in https://github.com/AcademySoftwareFoundation/OpenPBR/issues/143, this PR fixes up the stated roughness ranges to forbid roughness > 1.  It isn't useful to allow the roughness to exceed a soft-max at 1, as the appearance is unconvincing  (looks like fabric, as the microfacets are mostly vertical -- which is not "rough", and we have a dedicated fuzz layer for this kind of appearance).
=> Making roughness ranges all [0,1]

reference/open_pbr_surface.mtlx
Add volume shading support.
These parameters are used in the VDF.
- `transmission_depth`
- `transmission_scatter`
- `transmission_scatter_anisotropy`
This PR closes #154.
=> Add volume shading support

index.html
Based on https://github.com/AcademySoftwareFoundation/OpenPBR/issues/110.
I added this discussion as a sub-section of the "Reduction to a mixture of lobes" section, as it is also quite technical and seems to make the most sense in the context of trying to do an implementation of the layering.
=> Add a discussion of the difference between entering/exiting light transport

index.html, parametrization.md.html, reference/open_pbr_surface.mtlx
As discussed recently, it would be less ambiguous to name the diffuse roughness `base_diffuse_roughness`.
=> Rename base_roughness to base_diffuse_roughness

index.html
It was my understanding during the discussions that we prefered to rely on PRs and issues regarding future work, rather than notes in the specification. This PR therefore removes the "Future work" notes from the document, as well as a left over comment (former parameters of the coat).
=> Remove Future work notes and left over comments

README.md
As suggested during the discussions, this PR renames the link to the specification, and removes the link to the GitHub issues.
=> Rework readme links

reference/open_pbr_surface.mtlx
Subsurface weight has uifolder and uiname values switched.
**Fixes Issue**
* https://github.com/AcademySoftwareFoundation/OpenPBR/issues/183
=> Fix uifolder name for subsurface weight

index.html
Since it's a specification, not a paper making an argument based on methods and results..  Also this "conclusion" is fairly content-free, so not helpful.
=> Remove conclusion section

style/style.css
Just a trivial tweak to reduce whitespace between the teaser images and the TOC:
=> Slightly shift TOC closer to teaser image.

examples/open_pbr_default.mtlx
This changelist adds the coat_darkening input to our default material example, improving the visibility of this control in user testing.
=> Add coat_darkening to default example

reference/open_pbr_surface.mtlx
This changelist adds the `energy_compensation` setting to `oren_nayar_diffuse_bsdf` in the reference implementation for OpenPBR, leveraging the upcoming support for this feature in MaterialX 1.39.
In recent MaterialX TSC meetings, we've aligned on this naming convention for the new energy compensation feature in oren_nayar_diffuse_bsdf, and it now seems safe to move forward with this setting in OpenPBR v1.0.
=> Enable diffuse energy compensation

reference/open_pbr_surface.mtlx
Since the Maya team noted that they need this field in order to derive the node name (with correct capitalization and word break) to show in the editor:
>since the name of the node is open_pbr_surface, it will require custom code to turn it into "OpenPBR Surface".
>uiname metadata is already in the MaterialX specifications in the "[Custom Node Declaration NodeDef Elements](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/documents/Specification/MaterialX.Specification.md#custom-node-declaration-nodedef-elements)" section for MaterialX 1.39 and I see this as well in the old 1.38 specification. Feel free to add it to OpenPBR surface and I will make sure LookdevX uses it.
=> Add uiname field to .mtlx nodedef

reference/open_pbr_surface.mtlx
Without fix:
With fix:
(In the `MaterialXView` app though, I don't see the difference. I'm not sure why, perhaps the original code is being pulled somehow?).
=> Implement TIR fix in MaterialX

index.html
As discussed in https://github.com/AcademySoftwareFoundation/MaterialX/pull/1822#issuecomment-2127738467, the MaterialX implementation assumed that the `base_weight` acts as an overall multiplier of the EON BRDF. While in the OpenPBR spec, we had `base_weight` instead multiplying `base_color`.
In fact the MaterialX intepretation seems better, since then the `base_weight` functions as a linear modulation of the overall albedo, rather than doing something non-linear and dependent on the color. This PR makes the necessary changes to the wording/math of the spec to implement this.
=> Diffuse base_weight description changed to match MaterialX EON implementation

openpbr.bib
Updating the date to June.
Also forcing capitalization, so e.g. in journals (such as JCGT) which (annoyingly) render the titles by default as all lowercase, the capitalization of OpenPBR is retained, e.g. in JCGT:
=> Update BibTeX citation (date, and capitalization)

examples/open_pbr_default.mtlx
This changelist updates the OpenPBR default example, matching its values to the latest default values of the shading model.
=> Update OpenPBR default example

examples/open_pbr_default.mtlx, index.html, parametrization.md.html, reference/open_pbr_surface.mtlx
From 1.5 to 1.4.  
As this won't make much difference to the look in implementations that ignore the adjacent IORs of the film.
But for those that take it into account, this will make the film visible rather than invisible by default (since `specular_ior` is 1.5 by default, and `coat_ior` 1.6).
=> Change thin film IOR default

README.md
With links to
- MaterialX web viewer running OpenPBR default material
- OpenPBR-viewer project and web app
=> Add a "resources" section to the front page

index.html
Following the discussion of https://github.com/AcademySoftwareFoundation/OpenPBR/issues/85, I propose to add the wording:
=> Clarify formula for emission color

index.html, parametrization.md.html, reference/open_pbr_surface.mtlx
This changelist updates the types associated with physical color values for subsurface scattering in OpenPBR, aligning with the conclusions of recent threads on ASWF Slack channels.
- Change `subsurface_radius_scale` from a `vector3` to a `color3` in the specification, aligning with the MaterialX implementation of OpenPBR.
- Change the `radius` input of `subsurface_bsdf` from a `vector3` to a `color3` in the MaterialX implementation, aligning with the current definition of the `subsurface_bsdf` node in MaterialX 1.39.
=> Update subsurface color types
